#
# Vivado (TM) v2016.3 (64-bit)
#
# build_project.tcl: Tcl script for re-creating project 'eggtimer'
#
# Generated by Vivado on Mon Apr 05 12:34:18 -0400 2021
# IP Build 1681267 on Mon Oct 10 21:28:31 MDT 2016
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (build_project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "D:/elec3500labs/eggtimer/src/hdl/digit_counter.v"
#    "D:/elec3500labs/eggtimer/src/hdl/bcdto7segment.v"
#    "D:/elec3500labs/eggtimer/src/hdl/clock_divider.v"
#    "D:/elec3500labs/eggtimer/src/hdl/time_count.v"
#    "D:/elec3500labs/eggtimer/src/hdl/quad_sevenseg.v"
#    "D:/elec3500labs/eggtimer/src/hdl/debouncer.v"
#    "D:/elec3500labs/eggtimer/src/hdl/eggtimer.v"
#    "D:/elec3500labs/eggtimer/src/hdl/main_control.v"
#    "D:/elec3500labs/eggtimer/src/hdl/cooktime_count.v"
#    "D:/elec3500labs/eggtimer/eggtimer.srcs/sources_1/ip/clk_gen_5MHz/clk_gen_5MHz.xci"
#    "D:/elec3500labs/eggtimer/src/constr/Nexys4DDR_Master_Remote_Control.xdc"
#    "D:/elec3500labs/eggtimer/src/sim/downcounter_tb.v"
#    "D:/elec3500labs/eggtimer/src/hdl/clock_divider.v"
#    "D:/elec3500labs/eggtimer/src/hdl/digit_counter.v"
#    "D:/elec3500labs/eggtimer/src/sim/timer_test.v"
#    "D:/elec3500labs/eggtimer/src/hdl/clock_divider.v"
#    "D:/elec3500labs/eggtimer/src/hdl/digit_counter.v"
#    "D:/elec3500labs/eggtimer/src/hdl/time_count.v"
#    "D:/elec3500labs/eggtimer/src/hdl/cooktime_count.v"
#    "D:/elec3500labs/eggtimer/src/sim/cooktime_tb.v"
#    "D:/elec3500labs/eggtimer/src/hdl/cooktime_count.v"
#    "D:/elec3500labs/eggtimer/src/hdl/digit_counter.v"
#    "D:/elec3500labs/eggtimer/src/hdl/debouncer.v"
#    "D:/elec3500labs/eggtimer/src/hdl/clock_divider.v"
#    "D:/elec3500labs/eggtimer/src/sim/debouncer_tb.v"
#    "D:/elec3500labs/eggtimer/src/hdl/bcdto7segment.v"
#    "D:/elec3500labs/eggtimer/src/hdl/clock_divider.v"
#    "D:/elec3500labs/eggtimer/src/hdl/quad_sevenseg.v"
#    "D:/elec3500labs/eggtimer/src/sim/display_tb.v"
#    "D:/elec3500labs/eggtimer/src/hdl/debouncer.v"
#    "D:/elec3500labs/eggtimer/src/hdl/bcdto7segment.v"
#    "D:/elec3500labs/eggtimer/src/hdl/clock_divider.v"
#    "D:/elec3500labs/eggtimer/src/hdl/digit_counter.v"
#    "D:/elec3500labs/eggtimer/src/hdl/main_control.v"
#    "D:/elec3500labs/eggtimer/src/hdl/time_count.v"
#    "D:/elec3500labs/eggtimer/src/hdl/quad_sevenseg.v"
#    "D:/elec3500labs/eggtimer/src/hdl/cooktime_count.v"
#    "D:/elec3500labs/eggtimer/src/sim/eggtimer_tb.v"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

variable script_file
set script_file "build_project.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir" { incr i; set origin_dir [lindex $::argv $i] }
      "--help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Create project
create_project eggtimer ./eggtimer -part xc7a100tcsg324-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [get_projects eggtimer]
set_property "board_part" "digilentinc.com:nexys-a7-100t:part0:1.0" $obj
set_property "default_lib" "xil_defaultlib" $obj
set_property "ip_cache_permissions" "read write" $obj
set_property "ip_output_repo" "D:/elec3500labs/eggtimer/eggtimer.cache/ip" $obj
set_property "sim.ip.auto_export_scripts" "1" $obj
set_property "source_mgmt_mode" "DisplayOnly" $obj
set_property "xpm_libraries" "XPM_CDC" $obj
set_property "xsim.array_display_limit" "64" $obj
set_property "xsim.trace_limit" "65536" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/src/hdl/digit_counter.v"]"\
 "[file normalize "$origin_dir/src/hdl/bcdto7segment.v"]"\
 "[file normalize "$origin_dir/src/hdl/clock_divider.v"]"\
 "[file normalize "$origin_dir/src/hdl/time_count.v"]"\
 "[file normalize "$origin_dir/src/hdl/quad_sevenseg.v"]"\
 "[file normalize "$origin_dir/src/hdl/debouncer.v"]"\
 "[file normalize "$origin_dir/src/hdl/eggtimer.v"]"\
 "[file normalize "$origin_dir/src/hdl/main_control.v"]"\
 "[file normalize "$origin_dir/src/hdl/cooktime_count.v"]"\
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
set files [list \
 "[file normalize "$origin_dir/src/hdl/digit_counter.v"]"\
 "[file normalize "$origin_dir/src/hdl/bcdto7segment.v"]"\
 "[file normalize "$origin_dir/src/hdl/clock_divider.v"]"\
 "[file normalize "$origin_dir/src/hdl/time_count.v"]"\
 "[file normalize "$origin_dir/src/hdl/quad_sevenseg.v"]"\
 "[file normalize "$origin_dir/src/hdl/debouncer.v"]"\
 "[file normalize "$origin_dir/src/hdl/eggtimer.v"]"\
 "[file normalize "$origin_dir/src/hdl/main_control.v"]"\
 "[file normalize "$origin_dir/src/hdl/cooktime_count.v"]"\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "eggtimer" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/eggtimer.srcs/sources_1/ip/clk_gen_5MHz/clk_gen_5MHz.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
set files [list \
 "[file normalize "$origin_dir/eggtimer.srcs/sources_1/ip/clk_gen_5MHz/clk_gen_5MHz.xci"]"\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/src/constr/Nexys4DDR_Master_Remote_Control.xdc"]"
set file_imported [import_files -fileset constrs_1 $file]
set file "constr/Nexys4DDR_Master_Remote_Control.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'downcounter' fileset (if not found)
if {[string equal [get_filesets -quiet downcounter] ""]} {
  create_fileset -simset downcounter
}

# Set 'downcounter' fileset object
set obj [get_filesets downcounter]
set files [list \
 "[file normalize "$origin_dir/src/sim/downcounter_tb.v"]"\
 "[file normalize "$origin_dir/src/hdl/clock_divider.v"]"\
 "[file normalize "$origin_dir/src/hdl/digit_counter.v"]"\
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
set files [list \
 "[file normalize "$origin_dir/src/sim/downcounter_tb.v"]"\
 "[file normalize "$origin_dir/src/hdl/clock_divider.v"]"\
 "[file normalize "$origin_dir/src/hdl/digit_counter.v"]"\
]
set imported_files [import_files -fileset downcounter $files]

# Set 'downcounter' fileset file properties for remote files
# None

# Set 'downcounter' fileset file properties for local files
# None

# Set 'downcounter' fileset properties
set obj [get_filesets downcounter]
set_property "source_set" "" $obj
set_property "top" "downcounter_tb" $obj
set_property "transport_int_delay" "0" $obj
set_property "transport_path_delay" "0" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj

# Create 'timer' fileset (if not found)
if {[string equal [get_filesets -quiet timer] ""]} {
  create_fileset -simset timer
}

# Set 'timer' fileset object
set obj [get_filesets timer]
set files [list \
 "[file normalize "$origin_dir/src/sim/timer_test.v"]"\
 "[file normalize "$origin_dir/src/hdl/clock_divider.v"]"\
 "[file normalize "$origin_dir/src/hdl/digit_counter.v"]"\
 "[file normalize "$origin_dir/src/hdl/time_count.v"]"\
 "[file normalize "$origin_dir/src/hdl/cooktime_count.v"]"\
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
set files [list \
 "[file normalize "$origin_dir/src/sim/timer_test.v"]"\
 "[file normalize "$origin_dir/src/hdl/clock_divider.v"]"\
 "[file normalize "$origin_dir/src/hdl/digit_counter.v"]"\
 "[file normalize "$origin_dir/src/hdl/time_count.v"]"\
 "[file normalize "$origin_dir/src/hdl/cooktime_count.v"]"\
]
set imported_files [import_files -fileset timer $files]

# Set 'timer' fileset file properties for remote files
# None

# Set 'timer' fileset file properties for local files
# None

# Set 'timer' fileset properties
set obj [get_filesets timer]
set_property "source_set" "" $obj
set_property "top" "timer_test" $obj
set_property "transport_int_delay" "0" $obj
set_property "transport_path_delay" "0" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj

# Create 'cooktime' fileset (if not found)
if {[string equal [get_filesets -quiet cooktime] ""]} {
  create_fileset -simset cooktime
}

# Set 'cooktime' fileset object
set obj [get_filesets cooktime]
set files [list \
 "[file normalize "$origin_dir/src/sim/cooktime_tb.v"]"\
 "[file normalize "$origin_dir/src/hdl/cooktime_count.v"]"\
 "[file normalize "$origin_dir/src/hdl/digit_counter.v"]"\
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
set files [list \
 "[file normalize "$origin_dir/src/sim/cooktime_tb.v"]"\
 "[file normalize "$origin_dir/src/hdl/cooktime_count.v"]"\
 "[file normalize "$origin_dir/src/hdl/digit_counter.v"]"\
]
set imported_files [import_files -fileset cooktime $files]

# Set 'cooktime' fileset file properties for remote files
# None

# Set 'cooktime' fileset file properties for local files
# None

# Set 'cooktime' fileset properties
set obj [get_filesets cooktime]
set_property "source_set" "" $obj
set_property "top" "cooktime_tb" $obj
set_property "transport_int_delay" "0" $obj
set_property "transport_path_delay" "0" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj

# Create 'debouncer' fileset (if not found)
if {[string equal [get_filesets -quiet debouncer] ""]} {
  create_fileset -simset debouncer
}

# Set 'debouncer' fileset object
set obj [get_filesets debouncer]
set files [list \
 "[file normalize "$origin_dir/src/hdl/debouncer.v"]"\
 "[file normalize "$origin_dir/src/hdl/clock_divider.v"]"\
 "[file normalize "$origin_dir/src/sim/debouncer_tb.v"]"\
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
set files [list \
 "[file normalize "$origin_dir/src/hdl/debouncer.v"]"\
 "[file normalize "$origin_dir/src/hdl/clock_divider.v"]"\
 "[file normalize "$origin_dir/src/sim/debouncer_tb.v"]"\
]
set imported_files [import_files -fileset debouncer $files]

# Set 'debouncer' fileset file properties for remote files
# None

# Set 'debouncer' fileset file properties for local files
# None

# Set 'debouncer' fileset properties
set obj [get_filesets debouncer]
set_property "source_set" "" $obj
set_property "top" "debouncer_tb" $obj
set_property "transport_int_delay" "0" $obj
set_property "transport_path_delay" "0" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj

# Create 'display' fileset (if not found)
if {[string equal [get_filesets -quiet display] ""]} {
  create_fileset -simset display
}

# Set 'display' fileset object
set obj [get_filesets display]
set files [list \
 "[file normalize "$origin_dir/src/hdl/bcdto7segment.v"]"\
 "[file normalize "$origin_dir/src/hdl/clock_divider.v"]"\
 "[file normalize "$origin_dir/src/hdl/quad_sevenseg.v"]"\
 "[file normalize "$origin_dir/src/sim/display_tb.v"]"\
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
set files [list \
 "[file normalize "$origin_dir/src/hdl/bcdto7segment.v"]"\
 "[file normalize "$origin_dir/src/hdl/clock_divider.v"]"\
 "[file normalize "$origin_dir/src/hdl/quad_sevenseg.v"]"\
 "[file normalize "$origin_dir/src/sim/display_tb.v"]"\
]
set imported_files [import_files -fileset display $files]

# Set 'display' fileset file properties for remote files
# None

# Set 'display' fileset file properties for local files
# None

# Set 'display' fileset properties
set obj [get_filesets display]
set_property "source_set" "" $obj
set_property "top" "display_tb" $obj
set_property "transport_int_delay" "0" $obj
set_property "transport_path_delay" "0" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj

# Create 'eggtimer' fileset (if not found)
if {[string equal [get_filesets -quiet eggtimer] ""]} {
  create_fileset -simset eggtimer
}

# Set 'eggtimer' fileset object
set obj [get_filesets eggtimer]
set files [list \
 "[file normalize "$origin_dir/src/hdl/debouncer.v"]"\
 "[file normalize "$origin_dir/src/hdl/bcdto7segment.v"]"\
 "[file normalize "$origin_dir/src/hdl/clock_divider.v"]"\
 "[file normalize "$origin_dir/src/hdl/digit_counter.v"]"\
 "[file normalize "$origin_dir/src/hdl/main_control.v"]"\
 "[file normalize "$origin_dir/src/hdl/time_count.v"]"\
 "[file normalize "$origin_dir/src/hdl/quad_sevenseg.v"]"\
 "[file normalize "$origin_dir/src/hdl/cooktime_count.v"]"\
 "[file normalize "$origin_dir/src/sim/eggtimer_tb.v"]"\
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
set files [list \
 "[file normalize "$origin_dir/src/hdl/debouncer.v"]"\
 "[file normalize "$origin_dir/src/hdl/bcdto7segment.v"]"\
 "[file normalize "$origin_dir/src/hdl/clock_divider.v"]"\
 "[file normalize "$origin_dir/src/hdl/digit_counter.v"]"\
 "[file normalize "$origin_dir/src/hdl/main_control.v"]"\
 "[file normalize "$origin_dir/src/hdl/time_count.v"]"\
 "[file normalize "$origin_dir/src/hdl/quad_sevenseg.v"]"\
 "[file normalize "$origin_dir/src/hdl/cooktime_count.v"]"\
 "[file normalize "$origin_dir/src/sim/eggtimer_tb.v"]"\
]
set imported_files [import_files -fileset eggtimer $files]

# Set 'eggtimer' fileset file properties for remote files
# None

# Set 'eggtimer' fileset file properties for local files
# None

# Set 'eggtimer' fileset properties
set obj [get_filesets eggtimer]
set_property "source_set" "" $obj
set_property "top" "eggtimer_tb" $obj
set_property "transport_int_delay" "0" $obj
set_property "transport_path_delay" "0" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7a100tcsg324-1 -flow {Vivado Synthesis 2016} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2016" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property "needs_refresh" "1" $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7a100tcsg324-1 -flow {Vivado Implementation 2016} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2016" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "needs_refresh" "1" $obj
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:eggtimer"
